###################################
server.port=15000
##################mysql##################
chat4j.mysql.ip=127.0.0.1
chat4j.mysql.port=3306
chat4j.mysql.db=chat4j
chat4j.mysql.username=root
chat4j.mysql.password=123456
##################redis##################
chat4j.redis.host=127.0.0.1
chat4j.redis.port=6379
chat4j.redis.index=2
chat4j.redis.password=123456
##################wechat##################
chat4j.wechat.appid=
chat4j.wechat.appSecret=
chat4j.wechat.redirectUri=
##################url##################
chat4j.url.front=http://localhost:11000
chat4j.url.backend=http://localhost:15000
##################oss##################
chat4j.oss.type=3
chat4j.oss.minio.endpoint=http://1.14.68.127:9090/
chat4j.oss.minio.bucketName=chat4j
chat4j.oss.minio.accessKey=3hc4lzYjDGpj78rp16sl
chat4j.oss.minio.secretKey=xbU8RlByYQFKxgFxJVJCA4YrhSTj5VIJPSP63u1l
chat4j.oss.aliyun.endpoint=
chat4j.oss.aliyun.accessKey=
chat4j.oss.aliyun.secretKey=
chat4j.oss.aliyun.bucketName=
chat4j.oss.local.path=D:/project/oss/chat4j/
##################email##################
chat4j.mail.host=smtp.qq.com
chat4j.mail.port=587
chat4j.mail.username=2770063826@qq.com
chat4j.mail.password=gwrmkvvsnkztdehj
###################MQ##################
chat4j.rabbitmq.host=1.14.68.127
chat4j.rabbitmq.port=5672
chat4j.rabbitmq.username=jixer666rabbitmq
chat4j.rabbitmq.password=jixer666rabbitmq
chat4j.rabbitmq.concurrency=5
chat4j.rabbitmq.maxConcurrency=10
chat4j.rabbitmq.prefetch=1
chat4j.rabbitmq.ackMode=auto
chat4j.rabbitmq.retry.enable=true
chat4j.rabbitmq.retry.time=1000ms
chat4j.rabbitmq.retry.multiplier=1
chat4j.rabbitmq.retry.maxAttempts=3
chat4j.rabbitmq.retry.stateless=true
